CREATE TABLE Authors (
    AuthorID    INT IDENTITY(1,1) PRIMARY KEY,
    AuthorName  NVARCHAR(100) NOT NULL,
    Country     NVARCHAR(50)
);

USE BookStore;

SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE';